databases:
  - name: fixjs_db
    databaseName: fixjs_db
    user: alexander
    plan: free

services:
  - type: web
    name: fixjs_db
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    preDeployCommand:
    startCommand: "bundle exac rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fixjs_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync:false- key: WEB_CONCURRENCY
        value: 2
