default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: alexander
  password: <%= ENV['1234'] %>

development:
  <<: *default
  database: new_db

test:
  <<: *default
  database: test_guru2_test

production:
  <<: *default
  database: test_guru2_production
  username: test_guru2
  password: <%= ENV["TEST_GURU2_DATABASE_PASSWORD"] %>