default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host:     localhost
  database: test_guru2_development_pdn
  username: postgres
  password:
  template: template0

test:
  <<: *default
  host:     localhost
  database: test_guru2_test
  username: postgres
  password:
  template: template0
